const aboutData = {
    "intro": "I'm Andrew, the technical architect behind Creative Transmissions, dedicated to integrating the latest technologies into your web projects. With over 19 years in the tech sector, my expertise has evolved from IT to WordPress and PHP development, and now to groundbreaking work in advanced web development.",
    "intro2": "I specialize in integrating the latest tech into your projects, including WebXR, Geographical Systems, Social Graphs, Blockchain and Big Data. I thrive on innovation and am passionate about leveraging new tools and techniques to create faster and more efficient development processes. I'm highly focused, an excellent problem solver, and resilient in the face of challenges. My mission is to ensure that your web projects are not just current but future proof.",
    "specialising": "If you're looking for immersive 3D web experiences, you've come to the right place. I've been at the forefront of 3D WebXR development, creating interactive and engaging virtual environments. Whether it's for innovative NFT marketplaces or custom projects, I utilise advanced technologies like Three.js and WebXR to bring your vision to life.",
    "journey": "My career has been a fascinating exploration of web technologies. I founded Creative Transmissions in 2010, where I developed TransitQuote—a range of WordPress plugins that smartly leverage JavaScript for dynamic pricing in the courier and transport sectors. This venture has honed both my technical and leadership skills, as I've managed remote teams and implemented agile methodologies.",
    "mastering": "JavaScript is the backbone of modern web development, and I've mastered its use in various applications. From client-side interactions to server-side solutions, my JavaScript expertise is comprehensive. I have a particular fondness for Three.js, a library that enables incredible 3D graphics right in your web browser.",
    "initiative": "As the founder of 3DeSocial, an open-source project, my aim is to democratise 3D web experiences. The project focuses on enabling anyone to create and share immersive 3D and VR experiences using decentralised storage solutions. It's not just about adding a new feature; it's about pioneering a whole new dimension of web interaction.",
    "expertise": "Beyond web development, I've collaborated with Connexio, gaining deep insights into social graphs and analytics. This experience has endowed me with a unique perspective on how data can be leveraged to create more engaging and personalised user experiences.",
    "collaborate": "We're at an exciting crossroads where traditional web development is converging with awe-inspiring advancements in 3D and VR technologies. If you're looking to push the boundaries in 3D WebXR, APIs, or JavaScript frameworks like Three.js, let's connect and build something extraordinary together."
};

export default aboutData;